package com.linkedin.android.infra;

import com.linkedin.android.entities.company.CompanyIntent;
import com.linkedin.android.entities.group.GroupDiscussionIntent;
import com.linkedin.android.entities.group.GroupIntent;
import com.linkedin.android.entities.job.JobIntent;
import com.linkedin.android.entities.jymbii.JymbiiIntent;
import com.linkedin.android.entities.school.SchoolIntent;
import com.linkedin.android.feed.DeepLinkArticleIntent;
import com.linkedin.android.feed.actorlist.FeedActorListIntent;
import com.linkedin.android.feed.aggregate.AggregateIntent;
import com.linkedin.android.feed.channel.ChannelIntent;
import com.linkedin.android.feed.detail.FeedUpdateDetailIntent;
import com.linkedin.android.feed.followhub.FollowHubIntent;
import com.linkedin.android.feed.promptresponselist.FeedPromptResponseListIntent;
import com.linkedin.android.feed.shared.imageviewer.ImageViewerIntent;
import com.linkedin.android.feed.shared.videoviewer.VideoViewerIntent;
import com.linkedin.android.feed.updates.common.comment.detail.CommentDetailIntent;
import com.linkedin.android.feed.updates.common.likes.detail.LikesDetailIntent;
import com.linkedin.android.growth.InviteAcceptIntent;
import com.linkedin.android.growth.SendInviteIntent;
import com.linkedin.android.growth.abi.AbiIntent;
import com.linkedin.android.growth.abi.WyloIntent;
import com.linkedin.android.growth.boost.BoostIntent;
import com.linkedin.android.growth.heathrow.HeathrowIntent;
import com.linkedin.android.growth.login.LoginIntent;
import com.linkedin.android.growth.newtovoyager.organic.NewToVoyagerIntroIntent;
import com.linkedin.android.growth.onboarding.OnboardingIntent;
import com.linkedin.android.growth.onboarding.rbmf.RebuildMyFeedIntent;
import com.linkedin.android.growth.samsung.SamsungSyncConsentIntent;
import com.linkedin.android.growth.seo.samename.SameNameDirectoryIntent;
import com.linkedin.android.growth.smsreminderconsent.SmsReminderConsentIntent;
import com.linkedin.android.growth.takeover.TakeoverIntent;
import com.linkedin.android.home.HomeIntent;
import com.linkedin.android.identity.edit.ProfileEditDeeplinkIntent;
import com.linkedin.android.identity.guidededit.infra.shared.GuidedEditIntent;
import com.linkedin.android.identity.guidededit.pendingendorsement.PendingEndorsementIntent;
import com.linkedin.android.identity.me.contentanalytics.ContentAnalyticsIntentBuilder;
import com.linkedin.android.identity.me.wvmp.MeWvmpIntentBuilder;
import com.linkedin.android.identity.me.wvmp.privatemode.MeWvmpPrivateModeIntentBuilder;
import com.linkedin.android.identity.profile.ProfileViewIntent;
import com.linkedin.android.infra.settings.SettingsIntent;
import com.linkedin.android.infra.webviewer.WebViewerIntent;
import com.linkedin.android.l2m.deeplink.DeepLinkHelperIntent;
import com.linkedin.android.messaging.compose.ComposeIntent;
import com.linkedin.android.messaging.compose.InmailComposeIntent;
import com.linkedin.android.messaging.conversationlist.ConversationSearchListIntent;
import com.linkedin.android.messaging.messagelist.AttachmentViewerIntent;
import com.linkedin.android.messaging.messagelist.MessageListIntent;
import com.linkedin.android.messaging.participantdetails.AddParticipantIntent;
import com.linkedin.android.messaging.participantdetails.ParticipantDetailsIntent;
import com.linkedin.android.messaging.reconnect.ReconnectIntent;
import com.linkedin.android.messaging.stickers.StickerStoreIntent;
import com.linkedin.android.premium.PremiumActivityIntent;
import com.linkedin.android.premium.profinder.ProfinderServiceProposalActivityIntent;
import com.linkedin.android.publishing.reader.ArticleIntent;
import com.linkedin.android.publishing.sharing.ShareIntent;
import com.linkedin.android.publishing.sharing.linkpicker.LinkPickerIntent;
import com.linkedin.android.publishing.sharing.mentionpicker.MentionPickerIntent;
import com.linkedin.android.relationships.ConnectedIntent;
import com.linkedin.android.relationships.PymkIntent;
import com.linkedin.android.relationships.RelationshipsSecondaryIntent;
import com.linkedin.android.relationships.addConnections.AddConnectionsIntent;
import com.linkedin.android.relationships.connectFlow.AcceptedInvitationIntent;
import com.linkedin.android.relationships.invitationsConnectionsShared.ConnectionsIntent;
import com.linkedin.android.relationships.invitationsConnectionsShared.InvitationsIntent;
import com.linkedin.android.search.SearchIntent;
import com.linkedin.android.search.resourcelist.ResourceListIntent;
import javax.inject.Inject;

public final class IntentRegistry
{
  public final AbiIntent abi;
  public final AcceptedInvitationIntent acceptedInvitation;
  public final AddConnectionsIntent addConnectionsIntent;
  public final AddParticipantIntent addParticipantIntent;
  public final AggregateIntent aggregate;
  public final ArticleIntent article;
  public final DeepLinkArticleIntent articleDeepLink;
  public final AttachmentViewerIntent attachmentViewerIntent;
  public final BoostIntent boostIntent;
  public final ChannelIntent channel;
  public final PremiumActivityIntent chooser;
  public final CommentDetailIntent commentDetail;
  public final CompanyIntent company;
  public final ComposeIntent composeIntent;
  public final ConnectedIntent connected;
  public final ConnectionsIntent connections;
  public final ContentAnalyticsIntentBuilder contentAnalytics;
  public final ConversationSearchListIntent conversationSearchListIntent;
  public final DeepLinkHelperIntent deepLinkHelperIntent;
  public final FeedActorListIntent feedActorList;
  public final FeedPromptResponseListIntent feedPromptResponseListIntent;
  public final FeedUpdateDetailIntent feedUpdateDetail;
  public final FollowHubIntent followHubIntent;
  public final GroupIntent group;
  public final GroupDiscussionIntent groupDiscussion;
  public final GuidedEditIntent guidedEdit;
  public final HeathrowIntent heathrowIntent;
  public final HomeIntent home;
  public final ImageViewerIntent imageViewer;
  public final InmailComposeIntent inmailComposeIntent;
  public final InvitationsIntent invitations;
  public final InviteAcceptIntent inviteAccept;
  public final JobIntent job;
  public final JymbiiIntent jymbii;
  public final LikesDetailIntent likesDetailViewer;
  public final LinkPickerIntent linkPicker;
  public final LoginIntent login;
  public final MeWvmpIntentBuilder meWvmp;
  public final MeWvmpPrivateModeIntentBuilder meWvmpPrivateMode;
  public final MentionPickerIntent mentionPicker;
  public final MessageListIntent messageListIntent;
  public final NewToVoyagerIntroIntent newToVoyagerOrganicIntro;
  public final OnboardingIntent onboarding;
  public final ParticipantDetailsIntent participantDetailsIntent;
  public final PendingEndorsementIntent pendingEndorsements;
  public final ProfileEditDeeplinkIntent profileEditDeeplink;
  public final ProfileViewIntent profileView;
  public final ProfinderServiceProposalActivityIntent profinderServiceProposalActivityIntent;
  public final PymkIntent pymk;
  public final RebuildMyFeedIntent rebuildMyFeedIntent;
  public final ReconnectIntent reconnectIntent;
  public final RelationshipsSecondaryIntent relationshipsSecondaryIntent;
  public final ResourceListIntent resourceListIntent;
  public final SameNameDirectoryIntent sameNameDirectoryIntent;
  public final SamsungSyncConsentIntent samsungSyncConsentIntent;
  public final SchoolIntent school;
  public final SearchIntent search;
  public final SendInviteIntent sendInvite;
  public final SettingsIntent settings;
  public final ShareIntent share;
  public final SmsReminderConsentIntent smsReminderConsent;
  public final StickerStoreIntent stickerStoreIntent;
  public final TakeoverIntent takeover;
  public final VideoViewerIntent videoViewer;
  public final WebViewerIntent webViewer;
  public final WyloIntent wylo;
  
  @Inject
  public IntentRegistry(LoginIntent paramLoginIntent, OnboardingIntent paramOnboardingIntent, RebuildMyFeedIntent paramRebuildMyFeedIntent, AbiIntent paramAbiIntent, WyloIntent paramWyloIntent, InviteAcceptIntent paramInviteAcceptIntent, SendInviteIntent paramSendInviteIntent, HeathrowIntent paramHeathrowIntent, SmsReminderConsentIntent paramSmsReminderConsentIntent, HomeIntent paramHomeIntent, NewToVoyagerIntroIntent paramNewToVoyagerIntroIntent, SearchIntent paramSearchIntent, PremiumActivityIntent paramPremiumActivityIntent, RelationshipsSecondaryIntent paramRelationshipsSecondaryIntent, ShareIntent paramShareIntent, ChannelIntent paramChannelIntent, AggregateIntent paramAggregateIntent, ImageViewerIntent paramImageViewerIntent, LinkPickerIntent paramLinkPickerIntent, MentionPickerIntent paramMentionPickerIntent, SchoolIntent paramSchoolIntent, CompanyIntent paramCompanyIntent, ProfileViewIntent paramProfileViewIntent, WebViewerIntent paramWebViewerIntent, VideoViewerIntent paramVideoViewerIntent, JobIntent paramJobIntent, GroupIntent paramGroupIntent, LikesDetailIntent paramLikesDetailIntent, MessageListIntent paramMessageListIntent, ParticipantDetailsIntent paramParticipantDetailsIntent, AddParticipantIntent paramAddParticipantIntent, AttachmentViewerIntent paramAttachmentViewerIntent, ComposeIntent paramComposeIntent, InmailComposeIntent paramInmailComposeIntent, StickerStoreIntent paramStickerStoreIntent, ConversationSearchListIntent paramConversationSearchListIntent, FeedUpdateDetailIntent paramFeedUpdateDetailIntent, CommentDetailIntent paramCommentDetailIntent, DeepLinkHelperIntent paramDeepLinkHelperIntent, ConnectedIntent paramConnectedIntent, InvitationsIntent paramInvitationsIntent, ConnectionsIntent paramConnectionsIntent, AcceptedInvitationIntent paramAcceptedInvitationIntent, AddConnectionsIntent paramAddConnectionsIntent, PendingEndorsementIntent paramPendingEndorsementIntent, MeWvmpIntentBuilder paramMeWvmpIntentBuilder, MeWvmpPrivateModeIntentBuilder paramMeWvmpPrivateModeIntentBuilder, ContentAnalyticsIntentBuilder paramContentAnalyticsIntentBuilder, JymbiiIntent paramJymbiiIntent, GuidedEditIntent paramGuidedEditIntent, GroupDiscussionIntent paramGroupDiscussionIntent, ProfileEditDeeplinkIntent paramProfileEditDeeplinkIntent, SettingsIntent paramSettingsIntent, DeepLinkArticleIntent paramDeepLinkArticleIntent, ArticleIntent paramArticleIntent, FeedActorListIntent paramFeedActorListIntent, SamsungSyncConsentIntent paramSamsungSyncConsentIntent, SameNameDirectoryIntent paramSameNameDirectoryIntent, BoostIntent paramBoostIntent, ResourceListIntent paramResourceListIntent, PymkIntent paramPymkIntent, FollowHubIntent paramFollowHubIntent, TakeoverIntent paramTakeoverIntent, ReconnectIntent paramReconnectIntent, FeedPromptResponseListIntent paramFeedPromptResponseListIntent, ProfinderServiceProposalActivityIntent paramProfinderServiceProposalActivityIntent)
  {
    login = paramLoginIntent;
    onboarding = paramOnboardingIntent;
    rebuildMyFeedIntent = paramRebuildMyFeedIntent;
    abi = paramAbiIntent;
    wylo = paramWyloIntent;
    inviteAccept = paramInviteAcceptIntent;
    sendInvite = paramSendInviteIntent;
    heathrowIntent = paramHeathrowIntent;
    smsReminderConsent = paramSmsReminderConsentIntent;
    home = paramHomeIntent;
    newToVoyagerOrganicIntro = paramNewToVoyagerIntroIntent;
    search = paramSearchIntent;
    chooser = paramPremiumActivityIntent;
    relationshipsSecondaryIntent = paramRelationshipsSecondaryIntent;
    share = paramShareIntent;
    channel = paramChannelIntent;
    aggregate = paramAggregateIntent;
    imageViewer = paramImageViewerIntent;
    school = paramSchoolIntent;
    company = paramCompanyIntent;
    profileView = paramProfileViewIntent;
    webViewer = paramWebViewerIntent;
    videoViewer = paramVideoViewerIntent;
    job = paramJobIntent;
    group = paramGroupIntent;
    likesDetailViewer = paramLikesDetailIntent;
    messageListIntent = paramMessageListIntent;
    participantDetailsIntent = paramParticipantDetailsIntent;
    addParticipantIntent = paramAddParticipantIntent;
    attachmentViewerIntent = paramAttachmentViewerIntent;
    composeIntent = paramComposeIntent;
    inmailComposeIntent = paramInmailComposeIntent;
    stickerStoreIntent = paramStickerStoreIntent;
    conversationSearchListIntent = paramConversationSearchListIntent;
    pendingEndorsements = paramPendingEndorsementIntent;
    linkPicker = paramLinkPickerIntent;
    mentionPicker = paramMentionPickerIntent;
    feedUpdateDetail = paramFeedUpdateDetailIntent;
    commentDetail = paramCommentDetailIntent;
    deepLinkHelperIntent = paramDeepLinkHelperIntent;
    connected = paramConnectedIntent;
    invitations = paramInvitationsIntent;
    connections = paramConnectionsIntent;
    acceptedInvitation = paramAcceptedInvitationIntent;
    addConnectionsIntent = paramAddConnectionsIntent;
    meWvmp = paramMeWvmpIntentBuilder;
    meWvmpPrivateMode = paramMeWvmpPrivateModeIntentBuilder;
    contentAnalytics = paramContentAnalyticsIntentBuilder;
    jymbii = paramJymbiiIntent;
    guidedEdit = paramGuidedEditIntent;
    groupDiscussion = paramGroupDiscussionIntent;
    profileEditDeeplink = paramProfileEditDeeplinkIntent;
    settings = paramSettingsIntent;
    articleDeepLink = paramDeepLinkArticleIntent;
    article = paramArticleIntent;
    feedActorList = paramFeedActorListIntent;
    samsungSyncConsentIntent = paramSamsungSyncConsentIntent;
    sameNameDirectoryIntent = paramSameNameDirectoryIntent;
    boostIntent = paramBoostIntent;
    resourceListIntent = paramResourceListIntent;
    pymk = paramPymkIntent;
    takeover = paramTakeoverIntent;
    followHubIntent = paramFollowHubIntent;
    reconnectIntent = paramReconnectIntent;
    feedPromptResponseListIntent = paramFeedPromptResponseListIntent;
    profinderServiceProposalActivityIntent = paramProfinderServiceProposalActivityIntent;
  }
}

/* Location:
 * Qualified Name:     com.linkedin.android.infra.IntentRegistry
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */