package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzr<R extends Result>
  extends OptionalPendingResult<R>
{
  private final zzb<R> zzaiy;
  
  public zzr(PendingResult<R> paramPendingResult)
  {
    if (!(paramPendingResult instanceof zzb)) {
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }
    zzaiy = ((zzb)paramPendingResult);
  }
  
  public final R get()
  {
    if (zzaiy.isReady())
    {
      TimeUnit localTimeUnit = TimeUnit.MILLISECONDS;
      return zzaiy.await$140a99d0(localTimeUnit);
    }
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public final boolean isDone()
  {
    return zzaiy.isReady();
  }
  
  public final void setResultCallback(ResultCallback<? super R> paramResultCallback)
  {
    zzaiy.setResultCallback(paramResultCallback);
  }
  
  public final Integer zzpa()
  {
    return zzaiy.zzagR;
  }
}

/* Location:
 * Qualified Name:     com.google.android.gms.common.api.internal.zzr
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */